---
title: "Simple document"
author: Linshan Xie
date: 2024-10-24
output: github_document
---

```{r}
library(ggplot2)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal()+theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis")

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Load the key packages.
```{r}
library(tidyverse)
library(rvest)
library(readxl)
```

## writing my first function

as an example, here's a z-score computation
```{r}
x_vec = rnorm(25, mean = 10, sd = 3.5)

(x_vec - mean(x_vec)) / sd(x_vec)
```

Now i'll write a function to do this
```{r}
z_score = function(x){
  z = (x - mean(x)) / sd(x)
  return(z)
}

z_score(x = x_vec)
```
does this always work?
```{r, error=TRUE}
z_score(x = 3)
```

```{r,error=TRUE}
z_score(x=c("my","name","is","jeff"))
```

需要加上条件
```{r}
z_score = function(x){
  if(!is.numeric(x)){
    stop("x needs to be numeric")
  }
  
  if(length(x) < 5){
    stop("you need at least 5 numbers to compute z score")
  }
  
 z = (x - mean(x)) / sd(x)
 
 return(z)
}
```

```{r, error=TRUE}
z_score(x = 3)
```

```{r, error=TRUE}
z_score(x=c("my","name","is","jeff"))
```

## A new function

```{r}
mean_and_sd = function(x){
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  out_df = 
    tibble(
      mean = mean_x,
      sd = sd_x
    )
  
  return(out_df)
  
}
```

```{r}
mean_and_sd(x_vec)
```

## Check stuff using a simulation
```{r}
sim_df = 
  tibble(
    x = rnorm(30, 10, 5)
  )

sim_df |>
  summarize(
    mean = mean(x), 
    sd = sd(x)
  )
```

### create a simulation fuction to check mean and sd
```{r}
sim_mean_sd = function(sample_size, true_mean = 10, true_sd = 5){
  sim_df = 
    tibble(
      x = rnorm(sample_size, true_mean, true_sd))
  
  out_df = sim_df |>
    summarize(
      mean = mean(x), 
      sd = sd(x))
  
  return(out_df)
}
```

```{r}
sim_mean_sd(sample_size = 30, true_mean = 4, true_sd = 12)
```

```{r}
sim_mean_sd(sample_size = 30, true_mean = 4, true_sd = 12)
```

```{r}
sim_mean_sd(30, 16, 2)
```

```{r}
sim_mean_sd(330)
```

## revisit LoTR dataset
```{r}
fellowship_df = 
  read_excel("./data/LotR_Words.xlsx", range = "B3:D6") |>
  mutate(movie = "fellowship_ring")

two_towers = readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") |>
  mutate(movie = "two_towers")

return_king = readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") |>
  mutate(movie = "return_king")

```

Use a function to solve the problem
```{r}
lotr_import = function(cell_range, movie_title){
  movie_df = 
    read_excel("./data/LotR_Words.xlsx", range = cell_range) |>
    mutate(movie = movie_title) |>
    janitor::clean_names() |>
    pivot_longer(
      female:male,
      names_to = "sex",
      values_to = "words"
    ) |>
    select(movie, everything())
  
  return(movie_df)

}
```

```{r}
lotr_import(cell_range = "B3:D6", movie_title = "fellowship_ring")
```

```{r}
lotr_df = 
  bind_rows(
    lotr_import(cell_range = "B3:D6", movie_title = "fellowship_ring"),
    lotr_import(cell_range = "F3:H6", movie_title = "two_towers"),
    lotr_import(cell_range = "J3:L6", movie_title = "return_king")
  )
```

## NUSDH
```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = read_html(nsduh_url)

marj_table = 
  nsduh_html |> 
  html_table() |> 
  nth(1) |>
  slice(-1) |> 
  mutate(drug = "marj")

cocaine_table = 
  nsduh_html |> 
  html_table() |> 
  nth(4) |>
  slice(-1) |> 
  mutate(drug = "cocaine")

heroin_table = 
  nsduh_html |> 
  html_table() |> 
  nth(5) |>
  slice(-1) |> 
  mutate(drug = "heroin")
```

```{r}
nsduh_table_format = function(html, table_number, table_name) {
  out_table = 
    html |> 
    html_table() |> 
    nth(table_number) |>
    slice(-1) |> 
    mutate(drug = table_name)
  
  return(out_table)
}
```

```{r}
bind_rows(
nsduh_table_format(nsduh_html, 1, "marj"),
nsduh_table_format(nsduh_html, 4, "cocaine"),
nsduh_table_format(nsduh_html, 5, "heroin"))
```
















